### PR TITLE
Writing test

### PR DESCRIPTION
**Pull request by yzhang175**
Guys, I have tested all six countries.

Tested elements:
- Name
- Language
- Electricity
- Telephone
- Water
- Vaccinations
- Currency
- Neighbors

Screen Shot 2021-04-29 at 11 55 20 AM
Screen Shot 2021-04-29 at 11 55 26 AM
Screen Shot 2021-04-29 at 11 55 05 AM

### CODE REVIEW

**Review by jhuang60 — DISMISSED** [review]
lgtm, thank you!

**Review by hyang77 — COMMENTED** [review]
Looks like the test scripts don't require mongoose, fetch, and utils (from line 8-12) and you could remove them.

**Comment by wxie11** [comment]
Need to add a "test" command in the package.json file, so when we run `npm run test` under the main folder, the test actually runs automatically and will be easily used in the ci script. Thanks for testing all the countries!!!!

**Comment by yzhang175** [comment]
> Looks like the test scripts don't require mongoose, fetch, and utils (from line 8-12) and you could remove them.

**Comment by yzhang175** [comment]
Fixed, and pull a new request.

**Pull request closed without merging**
